[dev]
    autoLaunch = false

    command = "npm run front:build"
    framework = "#custom"
    targetPort = 3000

[build]
    plugins = ["dotenv-path"]

[[plugins]]
    package = "./netlify/plugins/dotenv-path"

[[edge_functions]]
    function = "user"
    path = "/{{PATHNAME_API}}/user"