[dev]
    autoLaunch = false
    command = "npm run start:front"
    framework = "#custom"
    targetPort = 3000

[build]
    command = "npm run build:front"
    plugins = ["dotenv-path"]

[[plugins]]
    package = "./netlify/plugins/dotenv-path"

[[edge_functions]]
    function = "user"
    path = "/{{PATHNAME_API}}/user"