[dev]
    autoLaunch = false

    command = "npm run front:build"
    framework = "#custom"
    targetPort = 3000

[build]
    plugins = ["./netlify/plugins/test"]

[[plugins]]
    package = "./netlify/plugins/test"

[[edge_functions]]
    function = "hello-world"
    path = "/{{PATHNAME_API}}/hello"