[dev]
    autoLaunch = false

    command = "npm run front:build"
    framework = "#custom"
    targetPort = 3000

[[plugins]]
    package = "./netlify/plugins/test"

[[edge_functions]]
    function = "hello-world"
    path = "/api/hello"