name: node

on:
  schedule:
    - cron: '00 06 * * *'
  workflow_dispatch:

jobs:
  # name
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node Setup
        uses: actions/setup-node@v2
        with:
          node-version: 14
          architecture: x64
      - run: npm install
      - run: npm start