on:
  schedule:
    - cron: '00 06 * * *'
jobs:
  runs-on: ${{ matrix.os }}
  strategy:
    matrix:
      os:
        - ubuntu-latest
      node_version:
        - 14
      architecture:
        - x64
  name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
  steps:
    - uses: actions/checkout@v2
    - name: Node Setup
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node_version }}
        architecture: ${{ matrix.architecture }}
    - run: npm install
    - run: npm start 